= VMWare IPI with Windows Machine Operator in a disconnected Openshift

== Preparation

=== Standard Openshift preparation
- DNS
- DHCP

=== Setup Quay Mirror Registry

. Download Quay Mirror Registry - https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
. Get a signed certificate, a wild card cert does work.
. Prepare a user on target machine to host Quay
  .. Make sure the user has sudo priviledges (visudo + wheel group)
  .. As the user do the following:
[source]  
----
ssh-keygen
ssh-copy-id quayhostname
sudo ./mirror-registry install --initUser quay --initPassword quayquay --quayHostname quayhostname --sslCert cert.pem --sslKey privkey.pem 
----
[start=4]
. Open firewall port for Quay, if firewall is in use
[code]
----
sudo --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload
----
[start=5]
. Create a new repository to host the mirror repository, using the web interface. In the following examples I am using "ocp", which will translate to "quay/ocp", ie. user/repo.

#### Setup Mirror process
. Download the Openshift Installer, client and mirror plugin:

[code]
----
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
tar xvf openshift-client-linux.tar.gz
tar xvf openshift-install-linux.tar.gz
tar xvf oc-mirror.tar.gz

----
[start=2]
. Configure security for pulling and pushing images:
[code]
----
mkdir ~/mirror
cd ~/mirror
<put your pullsecret copied form https://console.redhat.com/openshift/downloads in a file called pull-secret>
cat ./pull-secret | jq . > pull-secret.json

----

Append to the list of auths in the pull-secret.json,the registry credentails. The credentials can be generated through the Quay web site, as a logged in user - https://quayhostname:8443/user/quay?tab=settings, *Generate Encrypted Password*, then after entering password, *Docker Configuration* > View quay-auth.json :

[code]
----
      "auths": {
        "<mirror_registry>": { 
          "auth": "<credentials>", 
          "email": "you@example.com"
      },
----
[start=3]
. Create the following script, update required values OCP_RELEASE and LOCAL_REPOSITORY (from step 3 from setting up Quay). 
   Also comment out the relevant commands if you are going to use a fully disconnected Quay mirror.
   OCP_RELEASE can be obtained by running "oc version"
[code]
----
OCP_RELEASE=4.11.22
LOCAL_REGISTRY='quayhost:8443'
LOCAL_REPOSITORY='quay/ocp'
LOCAL_SECRET_JSON='pull-secret.json'
PRODUCT_REPO='openshift-release-dev'
RELEASE_NAME='ocp-release'
ARCHITECTURE=x86_64
REMOVABLE_MEDIA_PATH=$PWD/dump/

# Example to extract to local directory, to dump the images, transfer and use following command on remote to import
#oc adm release mirror -a ${LOCAL_SECRET_JSON} --to-dir=${REMOVABLE_MEDIA_PATH}/mirror quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE}

# Example to upload images from local directory, in the case of total disconnected install 
#oc image mirror -a ${LOCAL_SECRET_JSON} --from-dir=${REMOVABLE_MEDIA_PATH}/mirror "file://openshift/release:${OCP_RELEASE}*" ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}

# Registry to Registry mirror process
oc adm release mirror -a ${LOCAL_SECRET_JSON} --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}

#oc adm release extract -a ${LOCAL_SECRET_JSON} --command=openshift-install "${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}"
----
[start=4]
. Capture the output, of the mirror command. At the bottom take note of the 2 sets of configurations, the *imageContentSources* and the *ImageContentSourcePolicy* :
[code]
----
[openshift@bastion mirror]$ . ./mirror.sh 
info: Mirroring 172 images to bastion.pietersmalan.com:8443/quay/ocp ...
bastion.pietersmalan.com:8443/
  quay/ocp
    blobs:
......
phase 0:
  bastion.pietersmalan.com:8443 quay/ocp blobs=351 mounts=0 manifests=172 shared=5

info: Planning completed in 33.71s
......
info: Mirroring completed in 2m31.1s (96.06MB/s)

Success
Update image:  bastion.pietersmalan.com:8443/quay/ocp:4.11.7-x86_64
Mirror prefix: bastion.pietersmalan.com:8443/quay/ocp
Mirror prefix: bastion.pietersmalan.com:8443/quay/ocp:4.11.7-x86_64

To use the new mirrored repository to install, add the following section to the install-config.yaml:

imageContentSources:
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev


To use the new mirrored repository for upgrades, use the following to create an ImageContentSourcePolicy:

apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: example
spec:
  repositoryDigestMirrors:
  - mirrors:
    - bastion.pietersmalan.com:8443/quay/ocp
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - bastion.pietersmalan.com:8443/quay/ocp
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----


== OpenShift Installation
=== Install vCenter Certificates
[note]
Only required if vCenter does not use valid SSL certificates. 
[code]
----
mkdir ~/vccerts
cd ~/vccerts
wget --no-check-certificate https://vcsa.pietersmalan.com/certs/download.zip
sudo dnf install unzip -y
unzip download.zip
sudo cp certs/lin/* /etc/pki/ca-trust/source/anchors
sudo update-ca-trust extract

----
=== Create Manifests
. Create a seperate directory
[code]
----
mkdir ~/openshift
cd ~/openshift

----
[start=2]
. Create install-config.yaml
[code]
----
openshift-install create install-config
----
[note]
Supply all the answers as per usual install.

Sample:
[code]
----
[openshift@bastion openshift]$ openshift-install create install-config
? Platform vsphere
? vCenter vcsa.pietersmalan.com
? Username administrator@pietersmalan.com
? Password [? for help] ********
INFO Connecting to vCenter vcsa.pietersmalan.com  
INFO Defaulting to only available datacenter: Datacenter 
INFO Defaulting to only available cluster: Cluster 
INFO Defaulting to only available datastore: nvme 
INFO Defaulting to only available network: VM Network 
? Virtual IP Address for API 192.168.89.5
? Virtual IP Address for Ingress 192.168.89.6
? Base Domain pietersmalan.com
? Cluster Name os
? Pull Secret [? for help] ************
....
INFO Install-Config created in: .
----

[start=3]
. Modify install-config.yaml to point to mirror repository

Edit install-config.yaml and add the *imageContentSources:* as captured during the mirroring process:

[code]
----
platform:
  vsphere:
    apiVIP: 192.168.89.5
    cluster: Cluster
    datacenter: Datacenter
    defaultDatastore: nvme
    ingressVIP: 192.168.89.6
    network: VM Network
    username: administrator@pietersmalan.com
    vCenter: vcsa.pietersmalan.com
publish: External
pullSecret: '{"auths":
....
imageContentSources:
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

