:icons: font

= VMWare IPI with Windows Machine Operator in a disconnected Openshift

== Preparation

=== Standard Openshift preparation
- DNS
- DHCP

=== Setup Quay Mirror Registry

. Download Quay Mirror Registry - https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
. Get a signed certificate, a wild card cert does work.
. Prepare a user on target machine to host Quay
  .. Make sure the user has sudo priviledges (visudo + wheel group)
  .. As the user do the following:
[source]  
----
ssh-keygen
ssh-copy-id quayhostname
sudo ./mirror-registry install --initUser quay --initPassword quayquay --quayHostname quayhostname --sslCert cert.pem --sslKey privkey.pem 
----
[start=4]
. Open firewall port for Quay, if firewall is in use
[code]
----
sudo --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload
----

#### Setup Mirror process
NOTE: It is assumed that the mirror registry has access to the internet and the target private subnet where Openshift will be installed. If not the mirror process should be done with an export to a tar file, then imported into the mirror registry in the private subnet, using a copy the tar file. See https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-disconnected.html#mirroring-image-set-full 

. Download the Openshift Installer, client and mirror plugin:

[code]
----
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
tar xvf openshift-client-linux.tar.gz
tar xvf openshift-install-linux.tar.gz
tar xvf oc-mirror.tar.gz

----
[start=2]
. Configure security for pulling and pushing images:
[code]
----
mkdir ~/mirror
cd ~/mirror
<put your pullsecret copied form https://console.redhat.com/openshift/downloads in a file called pull-secret>
cat ./pull-secret | jq . > pull-secret.json

----

Append to the list of auths in the pull-secret.json, the local mirror registry credentails. The credentials can be generated through the Quay web site, as a logged in user - https://quayhostname:8443/user/quay?tab=settings, *Generate Encrypted Password*, then after entering password, *Docker Configuration* > View quay-auth.json :

[code]
----
      "auths": {
        "<mirror_registry>": { 
          "auth": "<credentials>", 
          "email": "you@example.com"
      },
----
[start=3]
. "Authenticate" against registry, to allow *oc mirror* access to all our registries involved:
   
[code]
----
mkdir ~/.docker
cp pull-secret.json ~/.docker/config.json
----

. Optional, check the availability of wmco in release 4.11, and the operator name, then query the available versions for operator:
[code]
----
oc-mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.11|grep windows
windows-machine-config-operator               Windows Machine Config Operator   stable

oc mirror list operators --package windows-machine-config-operator --catalog registry.redhat.io/redhat/redhat-operator-index:v4.11
PACKAGE                          CHANNEL  HEAD
windows-machine-config-operator  preview  windows-machine-config-operator.v6.0.0
windows-machine-config-operator  stable   windows-machine-config-operator.v6.0.0
----

[start=4]
. Create a template to start with, or copy the sample:
[code]
----
oc-mirror init --registry quayhost:8443/mirror/oc-mirror-metadata > imageset-config.yaml 
----

Modified contents of imageset-config.yaml, notice the imageURL, produced by the command above with required operators section added for wmco.

[code]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  registry:
    imageURL: bastion.pietersmalan.com:8443/mirror/oc-mirror-metdata
    skipTLS: false
mirror:
  platform:
    channels:
    - name: stable-4.11
      type: ocp
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
    packages:
    - name: windows-macine-config-operator
      channels:
      - name: stable
  additionalImages:
  - name: registry.redhat.io/ubi8/ubi:latest
  helm: {}
----

NOTE: For additional configuration, for example min/max version definitions etc, see https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-imageset-config-params_installing-mirroring-disconnected
[start=5]
. Start the mirror proces:
[code]
----
oc mirror --config=./imageset-config.yaml docker://bastion.pietersmalan.com:8443
----

The output would be similar to the following:
[code]
----
Checking push permissions for bastion.pietersmalan.com:8443
Creating directory: oc-mirror-workspace/src/publish
Creating directory: oc-mirror-workspace/src/v2
Creating directory: oc-mirror-workspace/src/charts
Creating directory: oc-mirror-workspace/src/release-signatures
No metadata detected, creating new workspace
wrote mirroring manifests to oc-mirror-workspace/operators.1667285372/manifests-redhat-operator-index

To upload local images to a registry, run:

	oc adm catalog mirror file://redhat/redhat-operator-index:v4.11 REGISTRY/REPOSITORY
bastion.pietersmalan.com:8443/
  openshift/release
    blobs:
      quay.io/openshift-release-dev/ocp-v4.0-art-dev sha256:d8190195889efb5333eeec18af9b6c82313edd4db62989bd3a357caca4f13f0e 1.404KiB
      quay.io/openshift-release-dev/ocp-v4.0-art-dev sha256:53525f8b521a5f9317c9ce853653e176e9ed1037575ae7f5da2a2bed6a450060 1.804KiB
      quay.io/openshift-release-dev/ocp-v4.0-art-dev sha256:17a7d9dcb5c2145df3d0adae108e5bfb9880760459672b1502bc363466740455 2.047KiB
.....
 manifests:
      sha256:94b611f00f51c9acc44ca3f4634e46bd79d7d28b46047c7e3389d250698f0c99 -> 4.11.9-x86_64
  openshift4-wincw/windows-machine-config-operator-bundle
    blobs:
      registry.redhat.io/openshift4-wincw/windows-machine-config-operator-bundle sha256:792a6efb36636881408b916f3b5c4ad22244bfba20619a6dc3fe76dba07de98c 4.984KiB
      registry.redhat.io/openshift4-wincw/windows-machine-config-operator-bundle sha256:711db228ba0f794e7092f376ebe937957b50e53931f676996cc17a2cb3133533 10.67KiB
    manifests:
      sha256:17b5c18bacb38a2e4d0c3e53e166857af9c53f9e02dd0416b34974c1376f4f5e -> 3bb4a030
  openshift4-wincw/windows-machine-config-rhel8-operator
......  
info: Mirroring completed in 3m26.03s (73.36MB/s)
Rendering catalog image "bastion.pietersmalan.com:8443/redhat/redhat-operator-index:v4.11" with file-based catalog 
Writing image mapping to oc-mirror-workspace/results-1667285694/mapping.txt
Writing CatalogSource manifests to oc-mirror-workspace/results-1667285694
Writing ICSP manifests to oc-mirror-workspace/results-1667285694
----

[start=6]
. Take not of the location of the  *ImageContentSourcePolicy* directory :
[code]
----
cd oc-mirror-workspace/results-1667285694
more imageContentSourcePolicy.yaml
pwd
----

== OpenShift Installation
=== Install vCenter Certificates
[note]
Only required if vCenter does not use valid SSL certificates. 
[code]
----
mkdir ~/vccerts
cd ~/vccerts
wget --no-check-certificate https://vcsa.pietersmalan.com/certs/download.zip
sudo dnf install unzip -y
unzip download.zip
sudo cp certs/lin/* /etc/pki/ca-trust/source/anchors
sudo update-ca-trust extract

----
=== Create ssh key
[note]
Only required if you want to access OpenShift nodes through ssh, in case of troubleshooting 
[code]
----
ssh-keygen
----
=== Create Manifests
. Create a seperate directory to host our configuration information, and in the end the cluster authentication details. 
[code]
----
mkdir ~/openshift
cd ~/openshift

----
[start=2]
. Create install-config.yaml
[code]
----
openshift-install create install-config
----
[note]
Supply all the answers as per usual install.

Sample:
[code]
----
[openshift@bastion openshift]$ openshift-install create install-config
? SSH Public Key /home/openshift/.ssh/id_rsa.pub
? Platform vsphere
? vCenter vcsa.pietersmalan.com
? Username administrator@pietersmalan.com
? Password [? for help] ********
INFO Connecting to vCenter vcsa.pietersmalan.com  
INFO Defaulting to only available datacenter: Datacenter 
INFO Defaulting to only available cluster: Cluster 
INFO Defaulting to only available datastore: nvme 
INFO Defaulting to only available network: VM Network 
? Virtual IP Address for API 192.168.89.5
? Virtual IP Address for Ingress 192.168.89.6
? Base Domain pietersmalan.com
? Cluster Name os
? Pull Secret [? for help] ************
....
INFO Install-Config created in: .
----

[start=3]
. Modify install-config.yaml to point to mirror repository

Edit install-config.yaml and add the *imageContentSourcePolicy* as captured during the mirroring process, by concatenating all the mirrors (everything under *repositoryDigestMirrors:* tags in *imageContentSourcePolicy.yaml), and make sure to change the NetworkType to OVNKubernetes from OpenShiftSDN:

[code]
----
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.89.5
    cluster: Cluster
    datacenter: Datacenter
    defaultDatastore: nvme
    ingressVIP: 192.168.89.6
    network: VM Network
    username: administrator@pietersmalan.com
    vCenter: vcsa.pietersmalan.com
publish: External
pullSecret: '{"auths":
....
imageContentSources:
- mirrors:
  - bastion.pietersmalan.com:8443/ubi8
    source: registry.redhat.io/ubi8
- mirrors:
  - bastion.pietersmalan.com:8443/openshift4-wincw
    source: registry.redhat.io/openshift4-wincw
- mirrors:
  - bastion.pietersmalan.com:8443/redhat
    source: registry.redhat.io/redhat
- mirrors:
  - bastion.pietersmalan.com:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pietersmalan.com:8443/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

[start=4]
. Creating the Kubernetes Manifests

WARNING: Make a backup of your install-config.yaml, outside of the working directory, as the install-config.yaml will be consumed when creating the manifests.

[code]
----
cd ~/openshift
cp install-config.yaml ..
openshift-install create manifests
----

The output from above command:
[code]
----
INFO Consuming Install Config from target directory 
INFO Manifests created in: manifests and openshift 
----

== Setup OVNKubernetes Hybrid Networking
. Create the network configuration manifest
[code]
----
cd ~/openshift
vi manifests/cluster-network-03-config.yaml
----

Add the following content, keeping in mind that you might have to change the cidr subnet value, if overlapping with existing network environment.
[code]
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  externalIP:
    policy: {}
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
  defaultNetwork:
    type: OVNKubernetes
    ovnKubernetesConfig:
      hybridOverlayConfig:
        hybridClusterNetwork:
        - cidr: 10.132.0.0/14
          hostPrefix: 23
        # Not supported with Windows 2019 LTSC
        hybridOverlayVXLANPort: 9898
----

Copy the imageContentSourcePolicy and catalogSource-redhat-operator-index to manifests, using the results directory captured int mirroring process:

[code]
----
cd ~/openshift
cp /home/openshift/mirror/oc-mirror-workspace/results-1667285694/*.yaml openshift
----

== Slip Stream the WMCO Operator

We can slip stream the WMCO Operator into the setup.

Files are available under manifests in repository.

. Create namespace for WMCO
[code]
----
cd ~/openshift
vi openshift/wmco-01-namespace.yaml
----

Insert the following code:

[code]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-windows-machine-config-operator 
  labels:
    openshift.io/cluster-monitoring: "true" 
----

[start=2]
. Create Operator Group for WMCO
[code]
----
cd ~/openshift
vi openshift/wmco-02-og.yaml
----

Insert the following code:

[code]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  targetNamespaces:
  - openshift-windows-machine-config-operator
----

[start=3]
. Create WCMO Subscription

[code]
----
cd ~/openshift
vi openshift/wmco-03-sub.yaml
----

Insert the following code:

[code]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  channel: "stable" 
  installPlanApproval: "Automatic" 
  name: "windows-machine-config-operator"
  source: "redhat-operators" 
  sourceNamespace: "openshift-marketplace" 
----

= Creating Cluster

The last step is to create the OpenShift Cluster

[code]
----
openshift-install create cluster
----

= Windows Configuration (BYO Node)

NOTE: Credits to John Tomaszewski - https://www.zews.org/ocp/win2022-worker/

Standard Windows Install.

On the Windows Node in Powershell:

[code]
----
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
Set-Service -Name sshd -StartupType 'Automatic'
Start-Service sshd
New-NetFirewallRule -Name "SSH" -DisplayName "SSH" -Description "Allow SSH" -Profile Any -Direction Inbound -Action Allow -Protocol TCP -Program Any -LocalAddress Any -RemoteAddress Any -LocalPort 22 -RemotePort Any 
New-NetFirewallRule -Name "OCPLOGS" -DisplayName "OCPLOGS" -Description "Allow OCP Log Collection" -Profile Any -Direction Inbound -Action Allow -Protocol TCP -Program Any -LocalAddress Any -RemoteAddress Any -LocalPort 10250 -RemotePort Any 
ssh-keygen
$authorizedkry = Get-Content -Path $env:USERPROFILE\.ssh\id_rsa.pub
$remotePowershell = "powershell Add-Content -Force -Path $env:ProgramData\ssh\administrators_authorized_keys -Value '$authorizedKey';icacls.exe ""$env:ProgramData\ssh\administrators_authorized_keys"" /inheritance:r /grant ""Administrators:F"" /grant ""SYSTEM:F"""
cd .\.ssh\
scp ./id_rsa openshift@openshiftinstallnode:~
----

Back on the installer node, using the id_rsa we have copied from Windows node:

[code]
----
oc create secret generic cloud-private-key --from-file=private-key.pem=id_rsa -n openshift-windows-machine-config-operator
----

Regsiter the Windows node, replace WINDOWSNODE_FQDN_OR_IP with Windows node ip, or fully qualified hostname: 

[code]
----
cat <<EOF > winnode.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: windows-instances
  namespace: openshift-windows-machine-config-operator
data:
  WINDOWSNODE_FQDN_OR_IP: |-
    username=Administrator
EOF
----

[code]
----
oc create -f winnode.yaml
----
