:icons: font

= VMWare IPI with Windows Machine Operator in a disconnected Openshift

== Preparation

=== Standard Openshift preparation
- DNS
- DHCP

=== Setup Quay Mirror Registry

. Download Quay Mirror Registry - https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
. Get a signed certificate, a wild card cert does work.
. Prepare a user on target machine to host Quay
  .. Make sure the user has sudo priviledges (visudo + wheel group)
  .. As the user do the following:
[source]  
----
ssh-keygen
ssh-copy-id quayhostname
sudo ./mirror-registry install --initUser quay --initPassword quayquay --quayHostname quayhostname --sslCert cert.pem --sslKey privkey.pem 
----
[start=4]
. Open firewall port for Quay, if firewall is in use
[code]
----
sudo --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload
----
[start=5]
. Create a new repository to host the mirror repository, using the web interface. In the following examples I am using "ocp", which will translate to "quay/ocp", ie. user/repo.

#### Setup Mirror process
. Download the Openshift Installer, client and mirror plugin:

[code]
----
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/oc-mirror.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
tar xvf openshift-client-linux.tar.gz
tar xvf openshift-install-linux.tar.gz
tar xvf oc-mirror.tar.gz

----
[start=2]
. Configure security for pulling and pushing images:
[code]
----
mkdir ~/mirror
cd ~/mirror
<put your pullsecret copied form https://console.redhat.com/openshift/downloads in a file called pull-secret>
cat ./pull-secret | jq . > pull-secret.json

----

Append to the list of auths in the pull-secret.json,the registry credentails. The credentials can be generated through the Quay web site, as a logged in user - https://quayhostname:8443/user/quay?tab=settings, *Generate Encrypted Password*, then after entering password, *Docker Configuration* > View quay-auth.json :

[code]
----
      "auths": {
        "<mirror_registry>": { 
          "auth": "<credentials>", 
          "email": "you@example.com"
      },
----
[start=3]
. Create the following script, update required values OCP_RELEASE and LOCAL_REPOSITORY (from step 3 from setting up Quay). 
   Also comment out the relevant commands if you are going to use a fully disconnected Quay mirror.
   OCP_RELEASE can be obtained by running "oc version"
[code]
----
OCP_RELEASE=4.11.22
LOCAL_REGISTRY='quayhost:8443'
LOCAL_REPOSITORY='quay/ocp'
LOCAL_SECRET_JSON='pull-secret.json'
PRODUCT_REPO='openshift-release-dev'
RELEASE_NAME='ocp-release'
ARCHITECTURE=x86_64
REMOVABLE_MEDIA_PATH=$PWD/dump/

# Example to extract to local directory, to dump the images, transfer and use following command on remote to import
#oc adm release mirror -a ${LOCAL_SECRET_JSON} --to-dir=${REMOVABLE_MEDIA_PATH}/mirror quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE}

# Example to upload images from local directory, in the case of total disconnected install 
#oc image mirror -a ${LOCAL_SECRET_JSON} --from-dir=${REMOVABLE_MEDIA_PATH}/mirror "file://openshift/release:${OCP_RELEASE}*" ${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}

# Registry to Registry mirror process
oc adm release mirror -a ${LOCAL_SECRET_JSON} --from=quay.io/${PRODUCT_REPO}/${RELEASE_NAME}:${OCP_RELEASE}-${ARCHITECTURE} --to=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY} --to-release-image=${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}

#oc adm release extract -a ${LOCAL_SECRET_JSON} --command=openshift-install "${LOCAL_REGISTRY}/${LOCAL_REPOSITORY}:${OCP_RELEASE}-${ARCHITECTURE}"
----
[start=4]
. Capture the output, of the mirror command. At the bottom take note of the 2 sets of configurations, the *imageContentSources* and the *ImageContentSourcePolicy* :
[code]
----
[openshift@bastion mirror]$ . ./mirror.sh 
info: Mirroring 172 images to bastion.pietersmalan.com:8443/quay/ocp ...
bastion.pietersmalan.com:8443/
  quay/ocp
    blobs:
......
phase 0:
  bastion.pietersmalan.com:8443 quay/ocp blobs=351 mounts=0 manifests=172 shared=5

info: Planning completed in 33.71s
......
info: Mirroring completed in 2m31.1s (96.06MB/s)

Success
Update image:  bastion.pietersmalan.com:8443/quay/ocp:4.11.7-x86_64
Mirror prefix: bastion.pietersmalan.com:8443/quay/ocp
Mirror prefix: bastion.pietersmalan.com:8443/quay/ocp:4.11.7-x86_64

To use the new mirrored repository to install, add the following section to the install-config.yaml:

imageContentSources:
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev


To use the new mirrored repository for upgrades, use the following to create an ImageContentSourcePolicy:

apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: example
spec:
  repositoryDigestMirrors:
  - mirrors:
    - bastion.pietersmalan.com:8443/quay/ocp
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - bastion.pietersmalan.com:8443/quay/ocp
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

TIP: For images not hosted on quay.io, you can setup also setup mirror, using the oc mirror plugin. An example used in the documentation is the Serverless Operator - https://docs.openshift.com/container-platform/4.11/installing/disconnected_install/installing-mirroring-disconnected.html

== OpenShift Installation
=== Install vCenter Certificates
[note]
Only required if vCenter does not use valid SSL certificates. 
[code]
----
mkdir ~/vccerts
cd ~/vccerts
wget --no-check-certificate https://vcsa.pietersmalan.com/certs/download.zip
sudo dnf install unzip -y
unzip download.zip
sudo cp certs/lin/* /etc/pki/ca-trust/source/anchors
sudo update-ca-trust extract

----
=== Create ssh key
[note]
Only required if you want to access OpenShift nodes through ssh, in case of troubleshooting 
[code]
----
ssh-keygen
----
=== Create Manifests
. Create a seperate directory to host our configuration information, and in the end the cluster authentication details. 
[code]
----
mkdir ~/openshift
cd ~/openshift

----
[start=2]
. Create install-config.yaml
[code]
----
openshift-install create install-config
----
[note]
Supply all the answers as per usual install.

Sample:
[code]
----
[openshift@bastion openshift]$ openshift-install create install-config
? SSH Public Key /home/openshift/.ssh/id_rsa.pub
? Platform vsphere
? vCenter vcsa.pietersmalan.com
? Username administrator@pietersmalan.com
? Password [? for help] ********
INFO Connecting to vCenter vcsa.pietersmalan.com  
INFO Defaulting to only available datacenter: Datacenter 
INFO Defaulting to only available cluster: Cluster 
INFO Defaulting to only available datastore: nvme 
INFO Defaulting to only available network: VM Network 
? Virtual IP Address for API 192.168.89.5
? Virtual IP Address for Ingress 192.168.89.6
? Base Domain pietersmalan.com
? Cluster Name os
? Pull Secret [? for help] ************
....
INFO Install-Config created in: .
----

[start=3]
. Modify install-config.yaml to point to mirror repository

Edit install-config.yaml and add the *imageContentSources:* as captured during the mirroring process, and make sure to change the NetworkType to OVNKubernetes from OpenShiftSDN:

[code]
----
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 192.168.89.5
    cluster: Cluster
    datacenter: Datacenter
    defaultDatastore: nvme
    ingressVIP: 192.168.89.6
    network: VM Network
    username: administrator@pietersmalan.com
    vCenter: vcsa.pietersmalan.com
publish: External
pullSecret: '{"auths":
....
imageContentSources:
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.pietersmalan.com:8443/quay/ocp
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

TIP: If you want to add other mirrors, you can add your own in the imageContentSource. If you need to add a repository with password, you can add the password in the pullSecret section, with a username:password base64 encoded. Keep in kind that adding the secret in the install-config, would mean that  any pull from your specified mirror across the cluster's projects, will be using the predefined secret, which may cause some security concerns.

[start=4]
. Creating the Kubernetes Manifests

WARNING: Make a backup of your install-config.yaml, outside of the working directory, as the install-config.yaml will be consumed when creating the manifests.

[code]
----
cp install-config.yaml ..
openshift-install create manifests
----

The output from above command:
[code]
----
INFO Consuming Install Config from target directory 
INFO Manifests created in: manifests and openshift 
----

== Setup OVNKubernetes Hybrid Networking
. Create the network configuration manifest
[code]
----
vi manifests/cluster-network-03-config.yaml
----

Add the following content, keeping in mind that you might have to change the cidr subnet value, if overlapping with existing network environment.
[code]
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  creationTimestamp: null
  name: cluster
spec:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  externalIP:
    policy: {}
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
  defaultNetwork:
    type: OVNKubernetes
    ovnKubernetesConfig:
      hybridOverlayConfig:
        hybridClusterNetwork:
        - cidr: 10.132.0.0/14
          hostPrefix: 23
        # Not supported with Windows 2019 LTSC
        hybridOverlayVXLANPort: 9898
----

== Slip Stream the WMCO Operator

We can slip stream the WMCO Operator into the setup.

Files are available under manifests in repository.

. Create namespace for WMCO
[code]
----
vi openshift/wmco-01-namespace.yaml
----

Insert the following code:

[code]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-windows-machine-config-operator 
  labels:
    openshift.io/cluster-monitoring: "true" 
----

[start=2]
. Create Operator Group for WMCO
[code]
----
vi openshift/wmco-02-og.yaml
----

Insert the following code:

[code]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  targetNamespaces:
  - openshift-windows-machine-config-operator
----

[start=3]
. Create WCMO Subscription

[code]
----
vi openshift/wmco-03-sub.yaml
----

Insert the following code:

[code]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  channel: "stable" 
  installPlanApproval: "Automatic" 
  name: "windows-machine-config-operator"
  source: "redhat-operators" 
  sourceNamespace: "openshift-marketplace" 
----

= Creating Cluster

The last step is to create the OpenShift Cluster

[code]
----
openshift-install create cluster
----

= Windows Configuration (BYO Node)

Credits to John Tomaszewski - https://www.zews.org/ocp/win2022-worker/

Standard Windows Install.

On the Windows Node in Powershell:

[code]
----
Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
Set-Service -Name sshd -StartupType 'Automatic'
Start-Service sshd
New-NetFirewallRule -Name "SSH" -DisplayName "SSH" -Description "Allow SSH" -Profile Any -Direction Inbound -Action Allow -Protocol TCP -Program Any -LocalAddress Any -RemoteAddress Any -LocalPort 22 -RemotePort Any 
New-NetFirewallRule -Name "OCPLOGS" -DisplayName "OCPLOGS" -Description "Allow OCP Log Collection" -Profile Any -Direction Inbound -Action Allow -Protocol TCP -Program Any -LocalAddress Any -RemoteAddress Any -LocalPort 10250 -RemotePort Any 
ssh-keygen
$authorizedkry = Get-Content -Path $env:USERPROFILE\.ssh\id_rsa.pub
$remotePowershell = "powershell Add-Content -Force -Path $env:ProgramData\ssh\administrators_authorized_keys -Value '$authorizedKey';icacls.exe ""$env:ProgramData\ssh\administrators_authorized_keys"" /inheritance:r /grant ""Administrators:F"" /grant ""SYSTEM:F"""
cd .\.ssh\
scp ./id_rsa openshift@openshiftinstallnode:~
----



[code]


